# Forzar solo Python
providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python3.11 app.py"
